# NumPy Cheat Sheet
A comprehensive, fully-executed reference for core NumPy operations — array creation, indexing, math, linear algebra, broadcasting, and more.

**Run all cells top to bottom** (or just read the outputs — they're already executed).

In [1]:
import numpy as np
np.__version__

'2.4.4'

## 1. Array Creation

In [2]:
# From lists
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(b)
print("shape:", b.shape, "| ndim:", b.ndim, "| dtype:", b.dtype, "| size:", b.size)

[1 2 3]
[[1 2 3]
 [4 5 6]]
shape: (2, 3) | ndim: 2 | dtype: int64 | size: 6


In [3]:
# Built-in generators
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2, 2), 7))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.empty((2, 2)))  # uninitialized memory

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.25 0.5 ]
 [0.75 1.  ]]


In [4]:
# Random arrays
rng = np.random.default_rng(42)  # preferred modern API (seeded for reproducibility)
print(rng.random((2, 3)))         # uniform [0,1)
print(rng.integers(0, 10, size=(2, 3)))  # random ints
print(rng.normal(0, 1, size=(2, 3)))     # normal distribution

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
[[7 7 7]
 [7 5 1]]
[[-0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934]]


## 2. Data Types (dtype)

In [5]:
a = np.array([1, 2, 3], dtype=np.float32)
print(a, a.dtype)

b = a.astype(np.int64)
print(b, b.dtype)

print(np.array([1, 2, 3]).dtype)      # int64 (platform default)
print(np.array([1.0, 2, 3]).dtype)    # float64
print(np.array([1, 2, 3], dtype=complex))

[1. 2. 3.] float32
[1 2 3] int64
int64
float64
[1.+0.j 2.+0.j 3.+0.j]


## 3. Inspecting Arrays

In [6]:
a = np.arange(24).reshape(4, 6)
print(a)
print("shape:", a.shape)
print("ndim:", a.ndim)
print("size:", a.size)
print("itemsize (bytes):", a.itemsize)
print("nbytes:", a.nbytes)
print("dtype:", a.dtype)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
shape: (4, 6)
ndim: 2
size: 24
itemsize (bytes): 8
nbytes: 192
dtype: int64


## 4. Indexing & Slicing

In [7]:
a = np.arange(10)
print(a[2])          # single element
print(a[2:7])        # slice
print(a[::2])        # step
print(a[::-1])        # reverse

2
[2 3 4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [8]:
m = np.arange(1, 13).reshape(3, 4)
print(m)
print(m[1, 2])        # row 1, col 2
print(m[0])            # first row
print(m[:, 1])         # second column
print(m[1:, 1:3])      # sub-matrix
print(m[-1])            # last row

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[1 2 3 4]
[ 2  6 10]
[[ 6  7]
 [10 11]]
[ 9 10 11 12]


In [9]:
# Boolean (mask) indexing
a = np.array([1, -2, 3, -4, 5])
print(a[a > 0])
a[a < 0] = 0
print(a)

[1 3 5]
[1 0 3 0 5]


In [10]:
# Fancy indexing
a = np.arange(10, 20)
idx = [0, 2, 4]
print(a[idx])

m = np.arange(12).reshape(3, 4)
print(m[[0, 2], [1, 3]])   # picks (0,1) and (2,3)

[10 12 14]
[ 1 11]


## 5. Reshaping & Manipulating Arrays

In [11]:
a = np.arange(12)
print(a.reshape(3, 4))
print(a.reshape(3, -1))     # -1 infers dimension
print(a.reshape(3, 4).T)     # transpose
print(a.reshape(3, 4).flatten())  # copy
print(a.reshape(3, 4).ravel())    # view when possible

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b]))
print(np.stack([a, b]))          # new axis
print(np.vstack([a, b]))
print(np.hstack([a, b]))
print(np.split(np.arange(9), 3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [13]:
a = np.arange(6)
print(np.expand_dims(a, axis=0).shape)  # (1, 6)
print(np.expand_dims(a, axis=1).shape)  # (6, 1)
print(a[:, np.newaxis].shape)            # same as above
print(np.squeeze(np.zeros((1, 3, 1))).shape)  # removes size-1 dims

(1, 6)
(6, 1)
(6, 1)
(3,)


## 6. Arithmetic & Universal Functions (ufuncs)

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b, a - b, a * b, a / b, a ** 2)
print(np.add(a, b), np.subtract(a, b), np.multiply(a, b))

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ] [1 4 9]
[5 7 9] [-3 -3 -3] [ 4 10 18]


In [15]:
a = np.array([1, 4, 9, 16])
print(np.sqrt(a))
print(np.exp(np.array([0, 1, 2])))
print(np.log(np.array([1, np.e, np.e**2])))
print(np.abs(np.array([-3, -1, 2])))
print(np.round(np.array([1.234, 5.678]), 1))
print(np.sin(np.array([0, np.pi/2, np.pi])))

[1. 2. 3. 4.]
[1.         2.71828183 7.3890561 ]
[0. 1. 2.]
[3 1 2]
[1.2 5.7]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


## 7. Aggregations & Statistics

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("sum:", a.sum(), "| sum axis0:", a.sum(axis=0), "| sum axis1:", a.sum(axis=1))
print("mean:", a.mean())
print("std:", a.std(), "| var:", a.var())
print("min:", a.min(), "| max:", a.max())
print("argmin:", a.argmin(), "| argmax:", a.argmax())
print("cumsum:", a.cumsum())
print("median:", np.median(a))
print("percentile 90:", np.percentile(a, 90))

sum: 21 | sum axis0: [5 7 9] | sum axis1: [ 6 15]
mean: 3.5
std: 1.707825127659933 | var: 2.9166666666666665
min: 1 | max: 6
argmin: 0 | argmax: 5
cumsum: [ 1  3  6 10 15 21]
median: 3.5
percentile 90: 5.5


## 8. Broadcasting

In [17]:
# Broadcasting lets NumPy operate on arrays of different shapes
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2,3)
b = np.array([10, 20, 30])             # shape (3,)  -> broadcast to (2,3)
print(a + b)

c = np.array([[1], [2]])               # shape (2,1) -> broadcast to (2,3)
print(a + c)

[[11 22 33]
 [14 25 36]]
[[2 3 4]
 [6 7 8]]


## 9. Linear Algebra (`np.linalg`)

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("matmul:\n", A @ B)            # or np.matmul(A, B)
print("dot:\n", np.dot(A, B))
print("transpose:\n", A.T)
print("determinant:", np.linalg.det(A))
print("inverse:\n", np.linalg.inv(A))
print("trace:", np.trace(A))

eigvals, eigvecs = np.linalg.eig(A)
print("eigenvalues:", eigvals)
print("eigenvectors:\n", eigvecs)

# Solve Ax = b
b_vec = np.array([1, 2])
x = np.linalg.solve(A, b_vec)
print("solution x:", x)

matmul:
 [[19 22]
 [43 50]]
dot:
 [[19 22]
 [43 50]]
transpose:
 [[1 3]
 [2 4]]
determinant: -2.0000000000000004
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
trace: 5
eigenvalues: [-0.37228132  5.37228132]
eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
solution x: [0.  0.5]


## 10. Sorting & Searching

In [19]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("sorted:", np.sort(a))
print("argsort:", np.argsort(a))
print("unique:", np.unique(a))
print("where >3:", np.where(a > 3))
print("values where >3:", a[np.where(a > 3)])
print("nonzero:", np.nonzero(a))
print("searchsorted:", np.searchsorted(np.sort(a), 4))

sorted: [1 1 2 3 4 5 6 9]
argsort: [1 3 6 0 2 4 7 5]
unique: [1 2 3 4 5 6 9]
where >3: (array([2, 4, 5, 7]),)
values where >3: [4 5 9 6]
nonzero: (array([0, 1, 2, 3, 4, 5, 6, 7]),)
searchsorted: 4


## 11. Set Operations

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("union:", np.union1d(a, b))
print("intersect:", np.intersect1d(a, b))
print("diff:", np.setdiff1d(a, b))
print("in1d:", np.isin(a, b))

union: [1 2 3 4 5 6]
intersect: [3 4]
diff: [1 2]
in1d: [False False  True  True]


## 12. Copies vs Views

In [21]:
a = np.arange(5)
view = a[1:4]        # view: shares memory
copy = a[1:4].copy()  # copy: independent memory

view[0] = 99
print("a after view edit:", a)   # a changes too

copy[0] = -1
print("a after copy edit:", a)   # a unaffected
print("np.shares_memory(a, view):", np.shares_memory(a, view))
print("np.shares_memory(a, copy):", np.shares_memory(a, copy))

a after view edit: [ 0 99  2  3  4]
a after copy edit: [ 0 99  2  3  4]
np.shares_memory(a, view): True
np.shares_memory(a, copy): False


## 13. Conditional Logic

In [22]:
a = np.array([1, -2, 3, -4, 5])
print(np.where(a > 0, a, 0))          # replace negatives with 0
print(np.select([a < 0, a == 0, a > 0], ["neg", "zero", "pos"], default="unknown"))
print(np.clip(a, -1, 3))               # clamp values to range

[1 0 3 0 5]
['pos' 'neg' 'pos' 'neg' 'pos']
[ 1 -1  3 -1  3]


## 14. Handling Missing / Special Values

In [23]:
a = np.array([1, np.nan, 3, np.inf, -np.inf])
print(np.isnan(a))
print(np.isinf(a))
print(np.nan_to_num(a, nan=0.0, posinf=999, neginf=-999))
print(np.nansum(np.array([1, np.nan, 3])))
print(np.nanmean(np.array([1, np.nan, 3])))

[False  True False False False]
[False False False  True  True]
[   1.    0.    3.  999. -999.]
4.0
2.0


## 15. Saving & Loading Arrays

In [24]:
a = np.arange(10)
np.save('/tmp/array.npy', a)
loaded = np.load('/tmp/array.npy')
print(loaded)

np.savetxt('/tmp/array.csv', a, delimiter=',')
loaded_csv = np.loadtxt('/tmp/array.csv', delimiter=',')
print(loaded_csv)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 16. Useful Random / Sampling Recipes

In [25]:
rng = np.random.default_rng(0)

print(rng.choice([10, 20, 30, 40], size=3, replace=False))  # sample without replacement
print(rng.permutation(np.arange(5)))                          # shuffle a copy
a = np.arange(5)
rng.shuffle(a)                                                  # shuffle in place
print(a)

[30 40 20]
[0 3 2 4 1]
[4 3 1 2 0]


## 17. Quick Reference Table

| Task | Function |
|---|---|
| Create array | `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()` |
| Shape info | `.shape`, `.ndim`, `.size`, `.dtype` |
| Reshape | `.reshape()`, `.T`, `.flatten()`, `.ravel()` |
| Combine | `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.stack()` |
| Math | `+ - * / **`, `np.sqrt()`, `np.exp()`, `np.log()` |
| Stats | `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()` |
| Linear algebra | `A @ B`, `np.linalg.inv()`, `np.linalg.det()`, `np.linalg.solve()` |
| Sort/search | `np.sort()`, `np.argsort()`, `np.where()`, `np.unique()` |
| Boolean mask | `a[a > x]` |
| Broadcasting | automatic shape alignment on ops |
| Save/load | `np.save()`, `np.load()`, `np.savetxt()`, `np.loadtxt()` |
