# NumPy Cheat Sheet
A comprehensive, fully-executed reference for core NumPy operations — array creation, indexing, math, linear algebra, broadcasting, and more. Every line has a comment explaining its use.

**Run all cells top to bottom** (or just read the outputs — they're already executed).

In [1]:
import numpy as np  # import numpy under the standard alias
np.__version__  # check installed numpy version

'2.4.4'

## 1. Array Creation

In [2]:
a = np.array([1, 2, 3])  # create a 1D array from a list
b = np.array([[1, 2, 3], [4, 5, 6]])  # create a 2D array from a nested list
print(a)  # display 1D array
print(b)  # display 2D array
print("shape:", b.shape, "| ndim:", b.ndim, "| dtype:", b.dtype, "| size:", b.size)  # inspect array metadata

[1 2 3]
[[1 2 3]
 [4 5 6]]
shape: (2, 3) | ndim: 2 | dtype: int64 | size: 6


In [3]:
print(np.zeros((2, 3)))  # array filled with zeros
print(np.ones((2, 3)))  # array filled with ones
print(np.full((2, 2), 7))  # array filled with a constant value
print(np.eye(3))  # identity matrix
print(np.arange(0, 10, 2))  # evenly spaced values by step size
print(np.linspace(0, 1, 5))  # evenly spaced values by count
print(np.empty((2, 2)))  # uninitialized array (fast, garbage values)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.25 0.5 ]
 [0.75 1.  ]]


In [4]:
rng = np.random.default_rng(42)  # create a seeded random generator (reproducible)
print(rng.random((2, 3)))  # uniform random floats in [0,1)
print(rng.integers(0, 10, size=(2, 3)))  # random integers in a range
print(rng.normal(0, 1, size=(2, 3)))  # random samples from normal distribution

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
[[7 7 7]
 [7 5 1]]
[[-0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934]]


## 2. Data Types (dtype)

In [5]:
a = np.array([1, 2, 3], dtype=np.float32)  # create array with explicit dtype
print(a, a.dtype)  # show array and its dtype

b = a.astype(np.int64)  # cast array to a different dtype
print(b, b.dtype)  # show casted array and new dtype

print(np.array([1, 2, 3]).dtype)  # default int dtype for integer literals
print(np.array([1.0, 2, 3]).dtype)  # default float dtype when a float is present
print(np.array([1, 2, 3], dtype=complex))  # force complex dtype

[1. 2. 3.] float32
[1 2 3] int64
int64
float64
[1.+0.j 2.+0.j 3.+0.j]


## 3. Inspecting Arrays

In [6]:
a = np.arange(24).reshape(4, 6)  # create a 4x6 array of sequential values
print(a)  # display the array
print("shape:", a.shape)  # dimensions of the array
print("ndim:", a.ndim)  # number of dimensions
print("size:", a.size)  # total number of elements
print("itemsize (bytes):", a.itemsize)  # bytes per element
print("nbytes:", a.nbytes)  # total bytes consumed by the array
print("dtype:", a.dtype)  # data type of elements

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
shape: (4, 6)
ndim: 2
size: 24
itemsize (bytes): 8
nbytes: 192
dtype: int64


## 4. Indexing & Slicing

In [7]:
a = np.arange(10)  # create a 1D array 0-9
print(a[2])  # single element access
print(a[2:7])  # slice a range of elements
print(a[::2])  # slice with a step (every 2nd element)
print(a[::-1])  # reverse the array

2
[2 3 4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [8]:
m = np.arange(1, 13).reshape(3, 4)  # create a 3x4 matrix
print(m)  # display the matrix
print(m[1, 2])  # access element at row 1, col 2
print(m[0])  # access first row
print(m[:, 1])  # access second column (all rows)
print(m[1:, 1:3])  # access a sub-matrix slice
print(m[-1])  # access last row

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[1 2 3 4]
[ 2  6 10]
[[ 6  7]
 [10 11]]
[ 9 10 11 12]


In [9]:
a = np.array([1, -2, 3, -4, 5])  # array with positive and negative values
print(a[a > 0])  # boolean mask: select only positive elements
a[a < 0] = 0  # boolean mask assignment: zero out negative elements
print(a)  # display modified array

[1 3 5]
[1 0 3 0 5]


In [10]:
a = np.arange(10, 20)  # array of values 10-19
idx = [0, 2, 4]  # list of indices to select
print(a[idx])  # fancy indexing: select elements at given indices

m = np.arange(12).reshape(3, 4)  # create a 3x4 matrix
print(m[[0, 2], [1, 3]])  # fancy indexing: picks (0,1) and (2,3)

[10 12 14]
[ 1 11]


## 5. Reshaping & Manipulating Arrays

In [11]:
a = np.arange(12)  # 1D array of 12 elements
print(a.reshape(3, 4))  # reshape into 3x4 matrix
print(a.reshape(3, -1))  # reshape with -1 to auto-infer that dimension
print(a.reshape(3, 4).T)  # transpose rows and columns
print(a.reshape(3, 4).flatten())  # flatten to 1D, returns a copy
print(a.reshape(3, 4).ravel())  # flatten to 1D, returns a view when possible

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
a = np.array([1, 2, 3])  # first array
b = np.array([4, 5, 6])  # second array
print(np.concatenate([a, b]))  # join arrays along an existing axis
print(np.stack([a, b]))  # join arrays along a new axis
print(np.vstack([a, b]))  # stack arrays vertically (row-wise)
print(np.hstack([a, b]))  # stack arrays horizontally (column-wise)
print(np.split(np.arange(9), 3))  # split an array into equal parts

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [13]:
a = np.arange(6)  # 1D array of 6 elements
print(np.expand_dims(a, axis=0).shape)  # add a new axis at position 0 -> (1, 6)
print(np.expand_dims(a, axis=1).shape)  # add a new axis at position 1 -> (6, 1)
print(a[:, np.newaxis].shape)  # same effect using np.newaxis
print(np.squeeze(np.zeros((1, 3, 1))).shape)  # remove all size-1 dimensions

(1, 6)
(6, 1)
(6, 1)
(3,)


## 6. Arithmetic & Universal Functions (ufuncs)

In [14]:
a = np.array([1, 2, 3])  # first array
b = np.array([4, 5, 6])  # second array
print(a + b, a - b, a * b, a / b, a ** 2)  # elementwise arithmetic operators
print(np.add(a, b), np.subtract(a, b), np.multiply(a, b))  # equivalent ufunc calls

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ] [1 4 9]
[5 7 9] [-3 -3 -3] [ 4 10 18]


In [15]:
a = np.array([1, 4, 9, 16])  # array of perfect squares
print(np.sqrt(a))  # elementwise square root
print(np.exp(np.array([0, 1, 2])))  # elementwise exponential (e^x)
print(np.log(np.array([1, np.e, np.e**2])))  # elementwise natural log
print(np.abs(np.array([-3, -1, 2])))  # elementwise absolute value
print(np.round(np.array([1.234, 5.678]), 1))  # round to given decimal places
print(np.sin(np.array([0, np.pi/2, np.pi])))  # elementwise sine

[1. 2. 3. 4.]
[1.         2.71828183 7.3890561 ]
[0. 1. 2.]
[3 1 2]
[1.2 5.7]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


## 7. Aggregations & Statistics

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array for aggregation examples
print("sum:", a.sum(), "| sum axis0:", a.sum(axis=0), "| sum axis1:", a.sum(axis=1))  # totals overall and per axis
print("mean:", a.mean())  # average of all elements
print("std:", a.std(), "| var:", a.var())  # standard deviation and variance
print("min:", a.min(), "| max:", a.max())  # smallest and largest values
print("argmin:", a.argmin(), "| argmax:", a.argmax())  # index of smallest/largest value
print("cumsum:", a.cumsum())  # running cumulative sum
print("median:", np.median(a))  # median value
print("percentile 90:", np.percentile(a, 90))  # 90th percentile value

sum: 21 | sum axis0: [5 7 9] | sum axis1: [ 6 15]
mean: 3.5
std: 1.707825127659933 | var: 2.9166666666666665
min: 1 | max: 6
argmin: 0 | argmax: 5
cumsum: [ 1  3  6 10 15 21]
median: 3.5
percentile 90: 5.5


## 8. Broadcasting

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2,3) array
b = np.array([10, 20, 30])  # shape (3,) array, broadcasts across rows of a
print(a + b)  # broadcasting: b is applied to every row of a

c = np.array([[1], [2]])  # shape (2,1) array, broadcasts across columns of a
print(a + c)  # broadcasting: c is applied to every column of a

[[11 22 33]
 [14 25 36]]
[[2 3 4]
 [6 7 8]]


## 9. Linear Algebra (`np.linalg`)

In [18]:
A = np.array([[1, 2], [3, 4]])  # first matrix
B = np.array([[5, 6], [7, 8]])  # second matrix

print("matmul:\n", A @ B)  # matrix multiplication (or np.matmul(A, B))
print("dot:\n", np.dot(A, B))  # dot product (same as matmul for 2D arrays)
print("transpose:\n", A.T)  # transpose of matrix A
print("determinant:", np.linalg.det(A))  # determinant of matrix A
print("inverse:\n", np.linalg.inv(A))  # inverse of matrix A
print("trace:", np.trace(A))  # sum of diagonal elements

eigvals, eigvecs = np.linalg.eig(A)  # compute eigenvalues and eigenvectors
print("eigenvalues:", eigvals)  # display eigenvalues
print("eigenvectors:\n", eigvecs)  # display eigenvectors

b_vec = np.array([1, 2])  # right-hand side vector for Ax = b
x = np.linalg.solve(A, b_vec)  # solve the linear system Ax = b
print("solution x:", x)  # display solution vector

matmul:
 [[19 22]
 [43 50]]
dot:
 [[19 22]
 [43 50]]
transpose:
 [[1 3]
 [2 4]]
determinant: -2.0000000000000004
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
trace: 5
eigenvalues: [-0.37228132  5.37228132]
eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
solution x: [0.  0.5]


## 10. Sorting & Searching

In [19]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])  # unsorted array with duplicates
print("sorted:", np.sort(a))  # return a sorted copy
print("argsort:", np.argsort(a))  # indices that would sort the array
print("unique:", np.unique(a))  # unique values, sorted
print("where >3:", np.where(a > 3))  # indices where condition is true
print("values where >3:", a[np.where(a > 3)])  # values matching condition
print("nonzero:", np.nonzero(a))  # indices of nonzero elements
print("searchsorted:", np.searchsorted(np.sort(a), 4))  # insertion index to keep array sorted

sorted: [1 1 2 3 4 5 6 9]
argsort: [1 3 6 0 2 4 7 5]
unique: [1 2 3 4 5 6 9]
where >3: (array([2, 4, 5, 7]),)
values where >3: [4 5 9 6]
nonzero: (array([0, 1, 2, 3, 4, 5, 6, 7]),)
searchsorted: 4


## 11. Set Operations

In [20]:
a = np.array([1, 2, 3, 4])  # first set of values
b = np.array([3, 4, 5, 6])  # second set of values
print("union:", np.union1d(a, b))  # all unique values from both arrays
print("intersect:", np.intersect1d(a, b))  # values common to both arrays
print("diff:", np.setdiff1d(a, b))  # values in a but not in b
print("in1d:", np.isin(a, b))  # boolean mask of a's elements found in b

union: [1 2 3 4 5 6]
intersect: [3 4]
diff: [1 2]
in1d: [False False  True  True]


## 12. Copies vs Views

In [21]:
a = np.arange(5)  # base array
view = a[1:4]  # slicing creates a view (shares memory with a)
copy = a[1:4].copy()  # .copy() creates an independent array

view[0] = 99  # modify the view
print("a after view edit:", a)  # a changes too since view shares memory

copy[0] = -1  # modify the copy
print("a after copy edit:", a)  # a unaffected since copy is independent
print("np.shares_memory(a, view):", np.shares_memory(a, view))  # confirm view shares memory with a
print("np.shares_memory(a, copy):", np.shares_memory(a, copy))  # confirm copy does not share memory

a after view edit: [ 0 99  2  3  4]
a after copy edit: [ 0 99  2  3  4]
np.shares_memory(a, view): True
np.shares_memory(a, copy): False


## 13. Conditional Logic

In [22]:
a = np.array([1, -2, 3, -4, 5])  # array with mixed sign values
print(np.where(a > 0, a, 0))  # replace negative values with 0, keep positives
print(np.select([a < 0, a == 0, a > 0], ["neg", "zero", "pos"], default="unknown"))  # multi-condition labeling
print(np.clip(a, -1, 3))  # clamp all values into the range [-1, 3]

[1 0 3 0 5]
['pos' 'neg' 'pos' 'neg' 'pos']
[ 1 -1  3 -1  3]


## 14. Handling Missing / Special Values

In [23]:
a = np.array([1, np.nan, 3, np.inf, -np.inf])  # array with NaN and infinities
print(np.isnan(a))  # boolean mask of NaN positions
print(np.isinf(a))  # boolean mask of infinite positions
print(np.nan_to_num(a, nan=0.0, posinf=999, neginf=-999))  # replace NaN/inf with finite values
print(np.nansum(np.array([1, np.nan, 3])))  # sum ignoring NaN values
print(np.nanmean(np.array([1, np.nan, 3])))  # mean ignoring NaN values

[False  True False False False]
[False False False  True  True]
[   1.    0.    3.  999. -999.]
4.0
2.0


## 15. Saving & Loading Arrays

In [24]:
a = np.arange(10)  # array to persist
np.save('/tmp/array.npy', a)  # save array to binary .npy file
loaded = np.load('/tmp/array.npy')  # load array back from .npy file
print(loaded)  # display loaded array

np.savetxt('/tmp/array.csv', a, delimiter=',')  # save array to a text/CSV file
loaded_csv = np.loadtxt('/tmp/array.csv', delimiter=',')  # load array back from CSV file
print(loaded_csv)  # display loaded array

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 16. Useful Random / Sampling Recipes

In [25]:
rng = np.random.default_rng(0)  # seeded random generator for reproducibility

print(rng.choice([10, 20, 30, 40], size=3, replace=False))  # random sample without replacement
print(rng.permutation(np.arange(5)))  # return a shuffled copy of the array
a = np.arange(5)  # array to shuffle in place
rng.shuffle(a)  # shuffle the array in place (modifies original)
print(a)  # display shuffled array

[30 40 20]
[0 3 2 4 1]
[4 3 1 2 0]


## 17. Quick Reference Table

| Task | Function |
|---|---|
| Create array | `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()` |
| Shape info | `.shape`, `.ndim`, `.size`, `.dtype` |
| Reshape | `.reshape()`, `.T`, `.flatten()`, `.ravel()` |
| Combine | `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.stack()` |
| Math | `+ - * / **`, `np.sqrt()`, `np.exp()`, `np.log()` |
| Stats | `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()` |
| Linear algebra | `A @ B`, `np.linalg.inv()`, `np.linalg.det()`, `np.linalg.solve()` |
| Sort/search | `np.sort()`, `np.argsort()`, `np.where()`, `np.unique()` |
| Boolean mask | `a[a > x]` |
| Broadcasting | automatic shape alignment on ops |
| Save/load | `np.save()`, `np.load()`, `np.savetxt()`, `np.loadtxt()` |
